name = "OptTestFun"
uuid = "9e838d01-880b-4c91-9151-a3029de357c0"
authors = ["AllanAmorim <150050564+AllanAmorim@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
